### PR TITLE
Added Login Page

### PR DESCRIPTION
**Pull request by Ankur9669**
image

### CODE REVIEW

**Review by zoef-yt — APPROVED** [review]
Nice use of comments. Love the UI it looks great. The code is good to merge.

**Comment by Sahil25061999** [comment]
My only suggestion would be to lighten the navbar shadow. the code looks good.

**Review by Sahil25061999 — APPROVED** [review]

**Comment by Ankur9669** [comment]
> My only suggestion would be to lighten the navbar shadow. the code looks good.

Done

**Comment by Ankur9669** [comment]
> Nice use of comments. Love the UI it looks great. The code is good to merge.

Thanks a lot😀

**Pull request merged**
