### PR TITLE
Added Home page

### PR DESCRIPTION
**Pull request by Ankur9669**

### CODE REVIEW

**Review by Naman-Saxena1 — CHANGES_REQUESTED** [review]
In responsive mode, hamburger Icon is breaking, even in browser console you are getting 404 error for hamburger icon.
Code looks fine, nice work on UI 😎

**Comment by iamalhera** [comment]
nice UI , fix hamburger issue

**Comment by Shivani-1524** [comment]
Just a suggestion to increase the visibility of difference between discounted and current price by maybe greying out the discounted text.
for reference:
image

**Comment by Ankur9669** [comment]
> In responsive mode, hamburger Icon is breaking, even in browser console you are getting 404 error for hamburger icon. Code looks fine, nice work on UI 😎

Done

**Comment by Ankur9669** [comment]
> nice UI , fix hamburger issue

Done

**Comment by Ankur9669** [comment]
> 

Understood but greying out the text would disturb my theme of the app but thanks for the suggestion i would look some alternatives for it later

**Pull request merged**
